# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-24 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mn',
            field=models.BigIntegerField(),
        ),
    ]
